/* ============================================================
   NOTICIAS GP3 (CAV + CCV) — alimentadas desde Instagram @gp3.sports.latam
   ------------------------------------------------------------
   Este archivo lo actualiza AUTOMÁTICAMENTE la tarea diaria
   "Noticias GP3 desde Instagram @gp3.sports.latam".
   Las noticias de aquí aparecen en las DOS páginas: cav.html y ccv.html.
   Las entradas generadas desde Instagram llevan el campo ig:"<shortcode>".
   Formato de cada entrada:
     { fecha:"AAAA-MM-DD", tag:"Categoría", title:"Título", text:"Resumen",
       imagen:"NOTICIAS-IG/<shortcode>.jpg", ig:"<shortcode>" }
   La más nueva va primero. No borrar entradas manualmente salvo error.
   ============================================================ */
window.GP3NEWS = [
 { fecha:"2026-08-17", tag:"Instagram", title:"Faltan 18 días para volver a pista. ⏱️ El campeonato se define acelerando.", text:"Faltan 18 días para volver a pista. ⏱️ El campeonato se define acelerando. San Juan Villicum · 4, 5 y 6 de septiembre. #RumboASanJuan #CAV #GP3Sports #MotociclismoArgentino", imagen:"NOTICIAS-IG/DcKLHqxlslk.jpg", ig:"DcKLHqxlslk" },
 { fecha:"2026-08-16", tag:"Instagram", title:"19 días. 🔥 Chile y Argentina se cruzan en el Villicum y nadie quiere quedarse afuera.", text:"19 días. 🔥 Chile y Argentina se cruzan en el Villicum y nadie quiere quedarse afuera. 5ta fecha · 4 al 6 de septiembre. #RumboASanJuan #CAV #CCV #GP3Sports #SanJuan", imagen:"NOTICIAS-IG/DcHmUmlIDzd.jpg", ig:"DcHmUmlIDzd" },
 { fecha:"2026-08-15", tag:"Instagram", title:"¡Empieza la cuenta regresiva! 🏁 Faltan 20 días para la 5ta fecha en San Juan Villicum. …", text:"¡Empieza la cuenta regresiva! 🏁 Faltan 20 días para la 5ta fecha en San Juan Villicum. CAV · CCV · Moto4, todos en una misma pista. 4, 5 y 6 de septiembre. #RumboASanJuan #CAV #CC", imagen:"NOTICIAS-IG/DcFBhxFligS.jpg", ig:"DcFBhxFligS" },
 { fecha:"2026-08-12", tag:"Instagram", title:"¿Quién ganará esta gran carrera: Chile o Argentina? 🇨🇱🇦🇷", text:"¿Quién ganará esta gran carrera: Chile o Argentina? 🇨🇱🇦🇷  Dos países, una misma pista y un duelo que promete 🔥🏁  🇨🇱 Vicente Kruger llega representando a Chile. 🇦🇷 Juan So", imagen:"NOTICIAS-IG/Db8olUtoWWf.jpg", ig:"Db8olUtoWWf" },
 { fecha:"2026-08-09", tag:"Instagram", title:"Resultados de la Carrera - 4a fecha CAV en el Autódromo Concordia. SBK Promocional: 1° S…", text:"Resultados de la Carrera - 4a fecha CAV en el Autódromo Concordia. SBK Promocional: 1° Sebastián Pablo, 2° Mauro Finco, 3° Tomás Galván. SBK Senior: 1° Gerardo Crisafulli, 2° Pedro", imagen:"NOTICIAS-IG/Db1DxurHda0.jpg", ig:"Db1DxurHda0" },
 { fecha:"2026-08-09", tag:"Instagram", title:"Resultados de la Carrera - 4a fecha CAV en el Autódromo Concordia. SBK Amateur: 1° Sergi…", text:"Resultados de la Carrera - 4a fecha CAV en el Autódromo Concordia. SBK Amateur: 1° Sergio Cocha, 2° Gabriel Juan. Sportbike: 1° Gastón Martínez, 2° Ignacio Lemos Becerro. SSP 600: ", imagen:"NOTICIAS-IG/Db0_nM8n7wq.jpg", ig:"Db0_nM8n7wq" },
 { fecha:"2026-08-09", tag:"Instagram", title:"Ranking 2026 - Así está el campeonato tras la 4a fecha CAV en el Autódromo Concordia. Lí…", text:"Ranking 2026 - Así está el campeonato tras la 4a fecha CAV en el Autódromo Concordia. Líderes: GP3 Experto Mariano Villalobos, GP3 Amateur Augusto Caviglia, GP3 Promocional Pablo T", imagen:"NOTICIAS-IG/Db1PelRnyGy.jpg", ig:"Db1PelRnyGy" },
 { fecha:"2026-08-09", tag:"Instagram", title:"Resultados de la Carrera - 4a fecha CAV en el Autódromo Concordia. SBK Pro: 1° Juan M. S…", text:"Resultados de la Carrera - 4a fecha CAV en el Autódromo Concordia. SBK Pro: 1° Juan M. Solorza, 2° Maximiliano Rocha, 3° Mateo Bongiovanni. SBK Experto: 1° Leonardo De Angelis, 2° ", imagen:"NOTICIAS-IG/Db1IYB0lANS.jpg", ig:"Db1IYB0lANS" },
 { fecha:"2026-08-09", tag:"Instagram", title:"Resultados de la Carrera - 4a fecha CAV en el Autódromo Concordia. GP3 Experto: 1° Maria…", text:"Resultados de la Carrera - 4a fecha CAV en el Autódromo Concordia. GP3 Experto: 1° Mariano Villalobos, 2° José María Plaja, 3° Ayrton Naveira. GP3 Amateur: 1° Augusto Caviglia, 2° ", imagen:"NOTICIAS-IG/Db07KUdgUoG.jpg", ig:"Db07KUdgUoG" },
 { fecha:"2026-08-08", tag:"Instagram", title:"Super Pole – Sportbike, SSP 600 y SBK Amateur: Gastón Martínez ganó en Sportbike y marcó…", text:"Super Pole – Sportbike, SSP 600 y SBK Amateur: Gastón Martínez ganó en Sportbike y marcó la mejor vuelta de la carrera (1'53.687), Eduardo Cundom se impuso en SSP 600 y Gabriel Jua", imagen:"NOTICIAS-IG/DbycW_5gQu8.jpg", ig:"DbycW_5gQu8" },
 { fecha:"2026-08-08", tag:"Instagram", title:"Super Pole GP3 – ¡Los dueños de la pole! Mariano Villalobos ganó la Super Pole de GP3 Ex…", text:"Super Pole GP3 – ¡Los dueños de la pole! Mariano Villalobos ganó la Super Pole de GP3 Experto por solo 409 milésimas sobre Plaja. Ramiro Cuadros dominó en GP3 Amateur y Fabricio Av", imagen:"NOTICIAS-IG/DbyacHQmnh6.jpg", ig:"DbyacHQmnh6" },
 { fecha:"2026-08-09", tag:"Instagram", title:"📋 Domingo de carreras en Concordia: warm up desde las 10:00 y las finales desde las 12:…", text:"📋 Domingo de carreras en Concordia: warm up desde las 10:00 y las finales desde las 12:30. 🏁 #CAV #Concordia #GP3Sports #MotociclismoArgentino #infoinscripcion", imagen:"NOTICIAS-IG/DbzG1Bpny04.jpg", ig:"DbzG1Bpny04" },
 { fecha:"2026-08-08", tag:"Instagram", title:"Podio Súper Pole – Así festejaron los 10 ganadores de la jornada en el Autódromo Concord…", text:"Podio Súper Pole – Así festejaron los 10 ganadores de la jornada en el Autódromo Concordia: Mariano Villalobos (GP3 Experto), Ramiro Cuadros (GP3 Amateur), Fabricio Avalos (GP3 Pro", imagen:"NOTICIAS-IG/Dby_N84H05c.jpg", ig:"Dby_N84H05c" },
 { fecha:"2026-08-08", tag:"Instagram", title:"Super Pole – SBK Pro y SBK Experto: Juan M. Solorza ganó en SBK Pro con la mejor vuelta …", text:"Super Pole – SBK Pro y SBK Experto: Juan M. Solorza ganó en SBK Pro con la mejor vuelta del fin de semana (1'42.042) y Francisco Vélez se quedó con la de SBK Experto tras un mano a", imagen:"NOTICIAS-IG/DbymUNlAfxm.jpg", ig:"DbymUNlAfxm" },
 { fecha:"2026-08-08", tag:"Instagram", title:"Super Pole – SBK Senior y SBK Promocional: Gerardo Crisafulli ganó en Senior con la mejo…", text:"Super Pole – SBK Senior y SBK Promocional: Gerardo Crisafulli ganó en Senior con la mejor vuelta de la carrera (1'51.076) y Sebastián Pablo se quedó con la Promocional. En pista lo", imagen:"NOTICIAS-IG/Dbyf_dhHz40.jpg", ig:"Dbyf_dhHz40" },
 { fecha:"2026-08-08", tag:"Instagram", title:"Clasificación Q1 – ¡Grilla definida en Concordia! Juan M. Solorza se quedó con la pole g…", text:"Clasificación Q1 – ¡Grilla definida en Concordia! Juan M. Solorza se quedó con la pole general con un registrazo de 1'42.752 en SBK Pro. Villalobos (GP3), Crisafulli (SBK Senior), ", imagen:"NOTICIAS-IG/DbyQ4tsAUOH.jpg", ig:"DbyQ4tsAUOH" },
 { fecha:"2026-08-08", tag:"Instagram", title:"5° Entrenamiento – Todas las categorías: Juan M. Solorza voló con 1'44.285 en SBK Pro, V…", text:"5° Entrenamiento – Todas las categorías: Juan M. Solorza voló con 1'44.285 en SBK Pro, Villalobos mandó en GP3 y Finco lideró SBK Promocional. El resumen completo de la mañana en u", imagen:"NOTICIAS-IG/DbyJ1RyH6vn.jpg", ig:"DbyJ1RyH6vn" },
 { fecha:"2026-08-07", tag:"Instagram", title:"GP3 Amateur – 2° Entrenamiento: Ramiro Cuadros sigue arriba con 2'10.278, escoltado por …", text:"GP3 Amateur – 2° Entrenamiento: Ramiro Cuadros sigue arriba con 2'10.278, escoltado por Augusto Caviglia. 4ª fecha CAV · Autódromo Concordia. #CAV #GP3Sports #Concordia #Motociclis", imagen:"NOTICIAS-IG/DbwHxScn1nk.jpg", ig:"DbwHxScn1nk" },
 { fecha:"2026-08-07", tag:"Instagram", title:"GP3 Experto – 2° Entrenamiento: Mariano Villalobos de nuevo al frente con 2'05.474, con …", text:"GP3 Experto – 2° Entrenamiento: Mariano Villalobos de nuevo al frente con 2'05.474, con Marquez y Naveira a menos de 2 segundos. 4ª fecha CAV · Autódromo Concordia. #CAV #GP3Sports", imagen:"NOTICIAS-IG/DbwHtgpH39g.jpg", ig:"DbwHtgpH39g" },
 { fecha:"2026-08-08", tag:"Instagram", title:"📋 Así se corre el sábado en Concordia: tandas, clasificación y Super Pole.", text:"📋 Así se corre el sábado en Concordia: tandas, clasificación y Super Pole. #CAV #Concordia #GP3Sports #infoinscripcion", imagen:"NOTICIAS-IG/DbwiBt5H10U.jpg", ig:"DbwiBt5H10U" },
 { fecha:"2026-08-07", tag:"Instagram", title:"HOY. Nos vemos en el Autódromo Ciudad de Concordia. 🏁 Entrada general $5.000 · menores …", text:"HOY. Nos vemos en el Autódromo Ciudad de Concordia. 🏁 Entrada general $5.000 · menores de 12 gratis. #CAV #EsHoy #Concordia #GP3Sports #infoinscripcion", imagen:"NOTICIAS-IG/DbwbKpCn5iD.jpg", ig:"DbwbKpCn5iD" },
 { fecha:"2026-08-07", tag:"Instagram", title:"SBK Experto – 1° Entrenamiento: Leonardo De Angelis al frente con 1'52.398, escoltado mu…", text:"SBK Experto – 1° Entrenamiento: Leonardo De Angelis al frente con 1'52.398, escoltado muy de cerca por Felipe Gini. 4ª fecha CAV · Autódromo Concordia. #CAV #GP3Sports #Concordia #", imagen:"NOTICIAS-IG/DbwFrkBnx5Q.jpg", ig:"DbwFrkBnx5Q" },
 { fecha:"2026-08-07", tag:"Instagram", title:"SBK Pro – 1° Entrenamiento: Juan M. Solorza marcó el mejor tiempo con 1'45.826, escoltad…", text:"SBK Pro – 1° Entrenamiento: Juan M. Solorza marcó el mejor tiempo con 1'45.826, escoltado por Maximiliano Rocha. 4ª fecha CAV · Autódromo Concordia. #CAV #GP3Sports #Concordia #Mot", imagen:"NOTICIAS-IG/DbwFoZFFJtE.jpg", ig:"DbwFoZFFJtE" },
 { fecha:"2026-08-07", tag:"Instagram", title:"¡ES HOY! 🏁 Arranca el Gran Premio Concordia, 4ª fecha del Campeonato Argentino de Veloc…", text:"¡ES HOY! 🏁 Arranca el Gran Premio Concordia, 4ª fecha del Campeonato Argentino de Velocidad. Te esperamos en el Autódromo Ciudad de Concordia · Entre Ríos. #CAV #EsHoy #Concordia ", imagen:"NOTICIAS-IG/DbvWf_0kwgB.jpg", ig:"DbvWf_0kwgB" },
 { fecha:"2026-08-07", tag:"Instagram", title:"📋 Mañana arranca el Gran Premio Concordia: este es el cronograma del viernes. Entrada a…", text:"📋 Mañana arranca el Gran Premio Concordia: este es el cronograma del viernes. Entrada al circuito desde las 07:00. #CAV #Concordia #GP3Sports #infoinscripcion", imagen:"NOTICIAS-IG/Dbt9OsGFgoJ.jpg", ig:"Dbt9OsGFgoJ" },
 { fecha:"2026-08-06", tag:"Instagram", title:"Mañana arranca todo. Tres días de velocidad en el Autódromo Ciudad de Concordia. 🔥", text:"Mañana arranca todo. Tres días de velocidad en el Autódromo Ciudad de Concordia. 🔥 #CAV #Concordia #GP3Sports #infoinscripcion", imagen:"NOTICIAS-IG/Dbt2XkBn-Sd.jpg", ig:"Dbt2XkBn-Sd" },
 { fecha:"2026-08-06", tag:"Instagram", title:"Falta 1 día. Mañana comienza el Gran Premio Concordia. 🔥", text:"Falta 1 día. Mañana comienza el Gran Premio Concordia. 🔥 Entrada general $5.000 · Parque Cerrado $20.000 · Menores de 12 gratis. #CAV #GP3Sports #Concordia #MotociclismoArgentino ", imagen:"NOTICIAS-IG/Dbsxs3LGuIX.jpg", ig:"Dbsxs3LGuIX" },
 { fecha:"2026-08-05", tag:"Instagram", title:"Faltan 2 días. El viernes arranca el Gran Premio Concordia. 🏍️", text:"Faltan 2 días. El viernes arranca el Gran Premio Concordia. 🏍️ #CAV #Concordia #GP3Sports #MotociclismoArgentino #infoinscripcion", imagen:"NOTICIAS-IG/DbrSw5djgi1.jpg", ig:"DbrSw5djgi1" },
 { fecha:"2026-08-05", tag:"Instagram", title:"¡Faltan solo 2 días! 🏍️ El Gran Premio Concordia ya se siente.", text:"¡Faltan solo 2 días! 🏍️ El Gran Premio Concordia ya se siente. Viernes, sábado y domingo · Autódromo Ciudad de Concordia. #CAV #Concordia #GP3Sports #Motociclismo #infoinscripcion", imagen:"NOTICIAS-IG/DbqOH7MDNvX.jpg", ig:"DbqOH7MDNvX" },
 { fecha:"2026-08-04", tag:"Instagram", title:"Concordia se prepara. ¿Y vos? Entrada general $5.000 · Parque Cerrado $20.000. 🎟️", text:"Concordia se prepara. ¿Y vos? Entrada general $5.000 · Parque Cerrado $20.000. 🎟️ #CAV #Concordia #GP3Sports #infoinscripcion", imagen:"NOTICIAS-IG/Dbot-EEE2cd.jpg", ig:"Dbot-EEE2cd" },
 { fecha:"2026-08-04", tag:"Instagram", title:"3 días. Tres jornadas de velocidad, adrenalina y emoción en Concordia. ⚡", text:"3 días. Tres jornadas de velocidad, adrenalina y emoción en Concordia. ⚡ 4ª fecha · Campeonato Argentino de Velocidad 2026. #CAV #GP3Sports #Concordia #MotociclismoArgentino #infoi", imagen:"NOTICIAS-IG/DbnpTyCje1v.jpg", ig:"DbnpTyCje1v" },
 { fecha:"2026-08-03", tag:"Instagram", title:"La calma antes de la tormenta. Última semana para agendarte: Gran Premio Concordia, 7 al…", text:"La calma antes de la tormenta. Última semana para agendarte: Gran Premio Concordia, 7 al 9 de agosto. 🗓️ #CAV #Concordia #GP3Sports #infoinscripcion", imagen:"NOTICIAS-IG/DbmJMTtH_jN.jpg", ig:"DbmJMTtH_jN" },
 { fecha:"2026-08-03", tag:"Instagram", title:"Faltan 4 días para que Entre Ríos vibre con el CAV. 🏁", text:"Faltan 4 días para que Entre Ríos vibre con el CAV. 🏁 Autódromo Ciudad de Concordia · 7, 8 y 9 de agosto. #CAV #EntreRios #Concordia #GP3Sports #infoinscripcion", imagen:"NOTICIAS-IG/DblEhIKkhe8.jpg", ig:"DblEhIKkhe8" },
 { fecha:"2026-08-02", tag:"Instagram", title:"Cada posición se pelea hasta el final. Así llega el campeonato a su 4ª fecha. 🏁 Concord…", text:"Cada posición se pelea hasta el final. Así llega el campeonato a su 4ª fecha. 🏁 Concordia, 7 al 9 de agosto. #CAV #GP3Sports #Concordia #infoinscripcion", imagen:"NOTICIAS-IG/DbjkYpMkSpf.jpg", ig:"DbjkYpMkSpf" },
 { fecha:"2026-08-02", tag:"Instagram", title:"5 días. 👨‍👩‍👧‍👦 Un plan para toda la familia: los menores de 12 años entran gratis a…", text:"5 días. 👨‍👩‍👧‍👦 Un plan para toda la familia: los menores de 12 años entran gratis acompañados por un adulto. Gran Premio Concordia · 7, 8 y 9 de agosto. #CAV #Concordia #GP3Sp", imagen:"NOTICIAS-IG/Dbiftolmm_7.jpg", ig:"Dbiftolmm_7" },
 { fecha:"2026-08-01", tag:"Instagram", title:"Adrenalina que no se cuenta, se siente. Vení a vivirla al lado de la pista. ⚡ 7 al 9 de …", text:"Adrenalina que no se cuenta, se siente. Vení a vivirla al lado de la pista. ⚡ 7 al 9 de agosto, Entre Ríos. #CAV #Concordia #MotociclismoArgentino", imagen:"NOTICIAS-IG/Dbg_l4Aj3wq.jpg", ig:"Dbg_l4Aj3wq" },
 { fecha:"2026-08-01", tag:"Instagram", title:"Faltan 6 días. Con la entrada Parque Cerrado ($20.000) recorrés los boxes y vivís el cam…", text:"Faltan 6 días. Con la entrada Parque Cerrado ($20.000) recorrés los boxes y vivís el campeonato por dentro. 🔧 7, 8 y 9 de agosto · Concordia. #CAV #ParqueCerrado #Concordia #GP3Sp", imagen:"NOTICIAS-IG/Dbf662sml5d.jpg", ig:"Dbf662sml5d" },
 { fecha:"2026-07-31", tag:"Instagram", title:"En 7 días ruge Concordia. 🔥 Agendá: 7, 8 y 9 de agosto, Autódromo Ciudad de Concordia.", text:"En 7 días ruge Concordia. 🔥 Agendá: 7, 8 y 9 de agosto, Autódromo Ciudad de Concordia. #CAV #GP3Sports #Concordia", imagen:"NOTICIAS-IG/DbeayytGN1Y.jpg", ig:"DbeayytGN1Y" },
 { fecha:"2026-07-31", tag:"Instagram", title:"¡Una semana! 🗓️ En 7 días arranca el Gran Premio Concordia, 4ª fecha del CAV 2026.", text:"¡Una semana! 🗓️ En 7 días arranca el Gran Premio Concordia, 4ª fecha del CAV 2026. Autódromo Ciudad de Concordia · Entre Ríos. #CAV #GP3Sports #Concordia #MotociclismoArgentino", imagen:"NOTICIAS-IG/DbdWIRVmq64.jpg", ig:"DbdWIRVmq64" },
 { fecha:"2026-07-30", tag:"Instagram", title:"Un plan para toda la familia: menores de 12 años gratis con un adulto y entrada general …", text:"Un plan para toda la familia: menores de 12 años gratis con un adulto y entrada general $5.000. 👪 Te esperamos en Concordia. #CAV #Concordia #GP3Sports", imagen:"NOTICIAS-IG/Dbb2Fuqj_eI.jpg", ig:"Dbb2Fuqj_eI" },
 { fecha:"2026-07-30", tag:"Instagram", title:"Faltan 8 días. 🎟️ Entrada general $5.000 — viví la velocidad de cerca.", text:"Faltan 8 días. 🎟️ Entrada general $5.000 — viví la velocidad de cerca. Gran Premio Concordia · 7, 8 y 9 de agosto. #CAV #Concordia #GP3Sports #Motociclismo", imagen:"NOTICIAS-IG/DbaxVNDFpED.jpg", ig:"DbaxVNDFpED" },
 { fecha:"2026-07-29", tag:"Instagram", title:"¿Querés ver las motos de cerca? Con la entrada Parque Cerrado ($20.000) recorrés los box…", text:"¿Querés ver las motos de cerca? Con la entrada Parque Cerrado ($20.000) recorrés los boxes por dentro. 🔧 7, 8 y 9 de agosto. #CAV #ParqueCerrado #Concordia #GP3Sports", imagen:"NOTICIAS-IG/DbZRNrqE41S.jpg", ig:"DbZRNrqE41S" },
 { fecha:"2026-07-29", tag:"Instagram", title:"9 días para que las principales categorías del motociclismo argentino salgan a pista en …", text:"9 días para que las principales categorías del motociclismo argentino salgan a pista en Concordia. 🏍️ 7, 8 y 9 de agosto · Autódromo Ciudad de Concordia. #CAV #CampeonatoArgentino", imagen:"NOTICIAS-IG/DbYMiYbGisT.jpg", ig:"DbYMiYbGisT" },
 { fecha:"2026-07-28", tag:"Instagram", title:"Talento en cada categoría: las principales categorías del motociclismo argentino en una …", text:"Talento en cada categoría: las principales categorías del motociclismo argentino en una misma pista. ⚡ Concordia, 7 al 9 de agosto. #CAV #MotociclismoArgentino #Concordia", imagen:"NOTICIAS-IG/DbWsZlDHENd.jpg", ig:"DbWsZlDHENd" },
 { fecha:"2026-07-28", tag:"Instagram", title:"Los mejores pilotos del país se preparan para Concordia. ⏱️ Faltan 10 días.", text:"Los mejores pilotos del país se preparan para Concordia. ⏱️ Faltan 10 días. 4ª fecha CAV · 7, 8 y 9 de agosto · Entre Ríos. #CAV #GP3Sports #Concordia #Motociclismo", imagen:"NOTICIAS-IG/DbVnvMzFqBE.jpg", ig:"DbVnvMzFqBE" },
 { fecha:"2026-07-27", tag:"Instagram", title:"Rueda a rueda, los mejores del país. Así se vive el CAV, y en Concordia se corre de nuev…", text:"Rueda a rueda, los mejores del país. Así se vive el CAV, y en Concordia se corre de nuevo. 🏍️ 7, 8 y 9 de agosto. #CAV #GP3Sports #Concordia", imagen:"NOTICIAS-IG/DbUHnlXH7pB.jpg", ig:"DbUHnlXH7pB" },
 { fecha:"2026-07-27", tag:"Instagram", title:"🏁 ¡Comienza la cuenta regresiva! Faltan 11 días para el Gran Premio Concordia, 4ª fecha…", text:"🏁 ¡Comienza la cuenta regresiva! Faltan 11 días para el Gran Premio Concordia, 4ª fecha del Campeonato Argentino de Velocidad. 7, 8 y 9 de agosto · Autódromo Ciudad de Concordia, ", imagen:"NOTICIAS-IG/DbTC9BakuWo.jpg", ig:"DbTC9BakuWo" },
 { fecha:"2026-07-26", tag:"Instagram", title:"La velocidad vuelve a Entre Ríos. 🏁 Nos vemos en el Gran Premio Concordia, 4ª fecha del…", text:"La velocidad vuelve a Entre Ríos. 🏁 Nos vemos en el Gran Premio Concordia, 4ª fecha del CAV. 7, 8 y 9 de agosto. #CAV #Concordia #GP3Sports #NosVemosEnConcordia", imagen:"NOTICIAS-IG/DbRi05RH7mL.jpg", ig:"DbRi05RH7mL" },
 { fecha:"2026-07-24", tag:"Instagram", title:"🏁 La temporada continúa en Concordia.", text:"🏁 La temporada continúa en Concordia.  La 4ª fecha del Campeonato Argentino de Velocidad 2026 ya está lista para recibir a pilotos, equipos y aficionados en un fin de semana donde", imagen:"NOTICIAS-IG/DbLTWxrI-MA.jpg", ig:"DbLTWxrI-MA" },
 { fecha:"2026-07-22", tag:"Instagram", title:"🏁 UN CIRCUITO. DOS CAMPEONATOS.", text:"🏁 UN CIRCUITO. DOS CAMPEONATOS.  El Campeonato Chileno de Velocidad ofrece dos formas de competir y dos desafíos únicos sobre una misma pista.  🇨🇱 Campeonato Nacional: reúne a l", imagen:"NOTICIAS-IG/DbGJxDaoNgz.jpg", ig:"DbGJxDaoNgz" },
 { fecha:"2026-07-21", tag:"Instagram", title:"🏁 EL CAMPEONATO SIGUE...", text:"🏁 EL CAMPEONATO SIGUE...  Tras las primeras fechas de la temporada, estos son los cinco pilotos con mayor puntaje acumulado en sus respectivas categorías.  Concordia será una fech", imagen:"NOTICIAS-IG/DbDk_I-o9zo.jpg", ig:"DbDk_I-o9zo" },
 { fecha:"2026-06-22", tag:"Instagram", title:"🏆 RANKING 2026 ACTUALIZADO | CAV 🇦🇷", text:"🏆 RANKING 2026 ACTUALIZADO | CAV 🇦🇷  Finalizada la tercera fecha del Campeonato Argentino de Velocidad en San Nicolás, así quedan las posiciones del campeonato en cada una de la", imagen:"NOTICIAS-IG/DZ3kVdSHB4Y.jpg", ig:"DZ3kVdSHB4Y" },
 { fecha:"2026-07-10", tag:"Instagram", title:"🏁 Un fin de semana. Miles de emociones.", text:"🏁 Un fin de semana. Miles de emociones.  Revive algunos de los mejores momentos de la última fecha del Campeonato Argentino de Velocidad en San Nicolás. 🏍️🔥", imagen:"NOTICIAS-IG/DaoFL7DIS7a.jpg", ig:"DaoFL7DIS7a" },
 { fecha:"2026-06-30", tag:"Instagram", title:"🏁 El Campeonato Argentino de Velocidad ya tiene su próximo destino.", text:"🏁 El Campeonato Argentino de Velocidad ya tiene su próximo destino.  Tras una intensa tercera fecha en San Nicolás, el CAV continúa su temporada 2026 con la mirada puesta en la 4.", imagen:"NOTICIAS-IG/DaOInjPIyHa.jpg", ig:"DaOInjPIyHa" },
 { fecha:"2026-07-17", tag:"Calendario", title:"Rumbo a Concordia: el CAV afina los últimos detalles", text:"Pilotos y equipos ya trabajan de cara a la próxima fecha del Campeonato Argentino de Velocidad en Concordia, del 7 al 9 de agosto. El campeonato se construye todos los días.", imagen:"NOTICIAS-IG/Da5VCLDIhiB.jpg", ig:"Da5VCLDIhiB" },
 { fecha:"2026-07-15", tag:"CCV Chile", title:"Más que velocidad: el compromiso detrás de cada piloto", text:"El Campeonato Chileno de Velocidad reúne no solo a los más rápidos, sino a quienes viven el deporte con esfuerzo, disciplina y pasión, a la espera de la próxima fecha.", imagen:"NOTICIAS-IG/Da0IZ-lomoy.jpg", ig:"Da0IZ-lomoy" },
 { fecha:"2026-07-14", tag:"CAV Argentina", title:"San Nicolás quedó atrás: la mira, puesta en Concordia", text:"Tras San Nicolás, el Campeonato Argentino de Velocidad afronta un nuevo capítulo de la temporada 2026 en Concordia, del 7 al 9 de agosto. Cada punto puede marcar la diferencia.", imagen:"NOTICIAS-IG/DaxjP-LIap2.jpg", ig:"DaxjP-LIap2" }
];
