/* ============================================================
   NOTICIAS GP3 (CAV + CCV) — alimentadas desde Instagram @gp3.sports.latam
   ------------------------------------------------------------
   Este archivo lo actualiza AUTOMÁTICAMENTE la tarea diaria
   "Noticias GP3 desde Instagram @gp3.sports.latam".
   Las noticias de aquí aparecen en las DOS páginas: cav.html y ccv.html.
   Las entradas generadas desde Instagram llevan el campo ig:"<shortcode>".
   Formato de cada entrada:
     { fecha:"AAAA-MM-DD", tag:"Categoría", title:"Título", text:"Resumen",
       imagen:"NOTICIAS-IG/<shortcode>.jpg", ig:"<shortcode>" }
   La más nueva va primero. No borrar entradas manualmente salvo error.
   ============================================================ */
window.GP3NEWS = [
 { fecha:"2026-08-03", tag:"Instagram", title:"La calma antes de la tormenta. Última semana para agendarte: Gran Premio Concordia, 7 al…", text:"La calma antes de la tormenta. Última semana para agendarte: Gran Premio Concordia, 7 al 9 de agosto. 🗓️ #CAV #Concordia #GP3Sports #infoinscripcion", imagen:"NOTICIAS-IG/DbmJMTtH_jN.jpg", ig:"DbmJMTtH_jN" },
 { fecha:"2026-08-03", tag:"Instagram", title:"Faltan 4 días para que Entre Ríos vibre con el CAV. 🏁", text:"Faltan 4 días para que Entre Ríos vibre con el CAV. 🏁 Autódromo Ciudad de Concordia · 7, 8 y 9 de agosto. #CAV #EntreRios #Concordia #GP3Sports #infoinscripcion", imagen:"NOTICIAS-IG/DblEhIKkhe8.jpg", ig:"DblEhIKkhe8" },
 { fecha:"2026-08-02", tag:"Instagram", title:"Cada posición se pelea hasta el final. Así llega el campeonato a su 4ª fecha. 🏁 Concord…", text:"Cada posición se pelea hasta el final. Así llega el campeonato a su 4ª fecha. 🏁 Concordia, 7 al 9 de agosto. #CAV #GP3Sports #Concordia #infoinscripcion", imagen:"NOTICIAS-IG/DbjkYpMkSpf.jpg", ig:"DbjkYpMkSpf" },
 { fecha:"2026-08-02", tag:"Instagram", title:"5 días. 👨‍👩‍👧‍👦 Un plan para toda la familia: los menores de 12 años entran gratis a…", text:"5 días. 👨‍👩‍👧‍👦 Un plan para toda la familia: los menores de 12 años entran gratis acompañados por un adulto. Gran Premio Concordia · 7, 8 y 9 de agosto. #CAV #Concordia #GP3Sp", imagen:"NOTICIAS-IG/Dbiftolmm_7.jpg", ig:"Dbiftolmm_7" },
 { fecha:"2026-08-01", tag:"Instagram", title:"Adrenalina que no se cuenta, se siente. Vení a vivirla al lado de la pista. ⚡ 7 al 9 de …", text:"Adrenalina que no se cuenta, se siente. Vení a vivirla al lado de la pista. ⚡ 7 al 9 de agosto, Entre Ríos. #CAV #Concordia #MotociclismoArgentino", imagen:"NOTICIAS-IG/Dbg_l4Aj3wq.jpg", ig:"Dbg_l4Aj3wq" },
 { fecha:"2026-08-01", tag:"Instagram", title:"Faltan 6 días. Con la entrada Parque Cerrado ($20.000) recorrés los boxes y vivís el cam…", text:"Faltan 6 días. Con la entrada Parque Cerrado ($20.000) recorrés los boxes y vivís el campeonato por dentro. 🔧 7, 8 y 9 de agosto · Concordia. #CAV #ParqueCerrado #Concordia #GP3Sp", imagen:"NOTICIAS-IG/Dbf662sml5d.jpg", ig:"Dbf662sml5d" },
 { fecha:"2026-07-31", tag:"Instagram", title:"En 7 días ruge Concordia. 🔥 Agendá: 7, 8 y 9 de agosto, Autódromo Ciudad de Concordia.", text:"En 7 días ruge Concordia. 🔥 Agendá: 7, 8 y 9 de agosto, Autódromo Ciudad de Concordia. #CAV #GP3Sports #Concordia", imagen:"NOTICIAS-IG/DbeayytGN1Y.jpg", ig:"DbeayytGN1Y" },
 { fecha:"2026-07-31", tag:"Instagram", title:"¡Una semana! 🗓️ En 7 días arranca el Gran Premio Concordia, 4ª fecha del CAV 2026.", text:"¡Una semana! 🗓️ En 7 días arranca el Gran Premio Concordia, 4ª fecha del CAV 2026. Autódromo Ciudad de Concordia · Entre Ríos. #CAV #GP3Sports #Concordia #MotociclismoArgentino", imagen:"NOTICIAS-IG/DbdWIRVmq64.jpg", ig:"DbdWIRVmq64" },
 { fecha:"2026-07-30", tag:"Instagram", title:"Un plan para toda la familia: menores de 12 años gratis con un adulto y entrada general …", text:"Un plan para toda la familia: menores de 12 años gratis con un adulto y entrada general $5.000. 👪 Te esperamos en Concordia. #CAV #Concordia #GP3Sports", imagen:"NOTICIAS-IG/Dbb2Fuqj_eI.jpg", ig:"Dbb2Fuqj_eI" },
 { fecha:"2026-07-30", tag:"Instagram", title:"Faltan 8 días. 🎟️ Entrada general $5.000 — viví la velocidad de cerca.", text:"Faltan 8 días. 🎟️ Entrada general $5.000 — viví la velocidad de cerca. Gran Premio Concordia · 7, 8 y 9 de agosto. #CAV #Concordia #GP3Sports #Motociclismo", imagen:"NOTICIAS-IG/DbaxVNDFpED.jpg", ig:"DbaxVNDFpED" },
 { fecha:"2026-07-29", tag:"Instagram", title:"¿Querés ver las motos de cerca? Con la entrada Parque Cerrado ($20.000) recorrés los box…", text:"¿Querés ver las motos de cerca? Con la entrada Parque Cerrado ($20.000) recorrés los boxes por dentro. 🔧 7, 8 y 9 de agosto. #CAV #ParqueCerrado #Concordia #GP3Sports", imagen:"NOTICIAS-IG/DbZRNrqE41S.jpg", ig:"DbZRNrqE41S" },
 { fecha:"2026-07-29", tag:"Instagram", title:"9 días para que las principales categorías del motociclismo argentino salgan a pista en …", text:"9 días para que las principales categorías del motociclismo argentino salgan a pista en Concordia. 🏍️ 7, 8 y 9 de agosto · Autódromo Ciudad de Concordia. #CAV #CampeonatoArgentino", imagen:"NOTICIAS-IG/DbYMiYbGisT.jpg", ig:"DbYMiYbGisT" },
 { fecha:"2026-07-28", tag:"Instagram", title:"Talento en cada categoría: las principales categorías del motociclismo argentino en una …", text:"Talento en cada categoría: las principales categorías del motociclismo argentino en una misma pista. ⚡ Concordia, 7 al 9 de agosto. #CAV #MotociclismoArgentino #Concordia", imagen:"NOTICIAS-IG/DbWsZlDHENd.jpg", ig:"DbWsZlDHENd" },
 { fecha:"2026-07-28", tag:"Instagram", title:"Los mejores pilotos del país se preparan para Concordia. ⏱️ Faltan 10 días.", text:"Los mejores pilotos del país se preparan para Concordia. ⏱️ Faltan 10 días. 4ª fecha CAV · 7, 8 y 9 de agosto · Entre Ríos. #CAV #GP3Sports #Concordia #Motociclismo", imagen:"NOTICIAS-IG/DbVnvMzFqBE.jpg", ig:"DbVnvMzFqBE" },
 { fecha:"2026-07-27", tag:"Instagram", title:"Rueda a rueda, los mejores del país. Así se vive el CAV, y en Concordia se corre de nuev…", text:"Rueda a rueda, los mejores del país. Así se vive el CAV, y en Concordia se corre de nuevo. 🏍️ 7, 8 y 9 de agosto. #CAV #GP3Sports #Concordia", imagen:"NOTICIAS-IG/DbUHnlXH7pB.jpg", ig:"DbUHnlXH7pB" },
 { fecha:"2026-07-27", tag:"Instagram", title:"🏁 ¡Comienza la cuenta regresiva! Faltan 11 días para el Gran Premio Concordia, 4ª fecha…", text:"🏁 ¡Comienza la cuenta regresiva! Faltan 11 días para el Gran Premio Concordia, 4ª fecha del Campeonato Argentino de Velocidad. 7, 8 y 9 de agosto · Autódromo Ciudad de Concordia, ", imagen:"NOTICIAS-IG/DbTC9BakuWo.jpg", ig:"DbTC9BakuWo" },
 { fecha:"2026-07-26", tag:"Instagram", title:"La velocidad vuelve a Entre Ríos. 🏁 Nos vemos en el Gran Premio Concordia, 4ª fecha del…", text:"La velocidad vuelve a Entre Ríos. 🏁 Nos vemos en el Gran Premio Concordia, 4ª fecha del CAV. 7, 8 y 9 de agosto. #CAV #Concordia #GP3Sports #NosVemosEnConcordia", imagen:"NOTICIAS-IG/DbRi05RH7mL.jpg", ig:"DbRi05RH7mL" },
 { fecha:"2026-07-24", tag:"Instagram", title:"🏁 La temporada continúa en Concordia.", text:"🏁 La temporada continúa en Concordia.  La 4ª fecha del Campeonato Argentino de Velocidad 2026 ya está lista para recibir a pilotos, equipos y aficionados en un fin de semana donde", imagen:"NOTICIAS-IG/DbLTWxrI-MA.jpg", ig:"DbLTWxrI-MA" },
 { fecha:"2026-07-22", tag:"Instagram", title:"🏁 UN CIRCUITO. DOS CAMPEONATOS.", text:"🏁 UN CIRCUITO. DOS CAMPEONATOS.  El Campeonato Chileno de Velocidad ofrece dos formas de competir y dos desafíos únicos sobre una misma pista.  🇨🇱 Campeonato Nacional: reúne a l", imagen:"NOTICIAS-IG/DbGJxDaoNgz.jpg", ig:"DbGJxDaoNgz" },
 { fecha:"2026-07-21", tag:"Instagram", title:"🏁 EL CAMPEONATO SIGUE...", text:"🏁 EL CAMPEONATO SIGUE...  Tras las primeras fechas de la temporada, estos son los cinco pilotos con mayor puntaje acumulado en sus respectivas categorías.  Concordia será una fech", imagen:"NOTICIAS-IG/DbDk_I-o9zo.jpg", ig:"DbDk_I-o9zo" },
 { fecha:"2026-06-22", tag:"Instagram", title:"🏆 RANKING 2026 ACTUALIZADO | CAV 🇦🇷", text:"🏆 RANKING 2026 ACTUALIZADO | CAV 🇦🇷  Finalizada la tercera fecha del Campeonato Argentino de Velocidad en San Nicolás, así quedan las posiciones del campeonato en cada una de la", imagen:"NOTICIAS-IG/DZ3kVdSHB4Y.jpg", ig:"DZ3kVdSHB4Y" },
 { fecha:"2026-07-10", tag:"Instagram", title:"🏁 Un fin de semana. Miles de emociones.", text:"🏁 Un fin de semana. Miles de emociones.  Revive algunos de los mejores momentos de la última fecha del Campeonato Argentino de Velocidad en San Nicolás. 🏍️🔥", imagen:"NOTICIAS-IG/DaoFL7DIS7a.jpg", ig:"DaoFL7DIS7a" },
 { fecha:"2026-06-30", tag:"Instagram", title:"🏁 El Campeonato Argentino de Velocidad ya tiene su próximo destino.", text:"🏁 El Campeonato Argentino de Velocidad ya tiene su próximo destino.  Tras una intensa tercera fecha en San Nicolás, el CAV continúa su temporada 2026 con la mirada puesta en la 4.", imagen:"NOTICIAS-IG/DaOInjPIyHa.jpg", ig:"DaOInjPIyHa" },
 { fecha:"2026-07-17", tag:"Calendario", title:"Rumbo a Concordia: el CAV afina los últimos detalles", text:"Pilotos y equipos ya trabajan de cara a la próxima fecha del Campeonato Argentino de Velocidad en Concordia, del 7 al 9 de agosto. El campeonato se construye todos los días.", imagen:"NOTICIAS-IG/Da5VCLDIhiB.jpg", ig:"Da5VCLDIhiB" },
 { fecha:"2026-07-15", tag:"CCV Chile", title:"Más que velocidad: el compromiso detrás de cada piloto", text:"El Campeonato Chileno de Velocidad reúne no solo a los más rápidos, sino a quienes viven el deporte con esfuerzo, disciplina y pasión, a la espera de la próxima fecha.", imagen:"NOTICIAS-IG/Da0IZ-lomoy.jpg", ig:"Da0IZ-lomoy" },
 { fecha:"2026-07-14", tag:"CAV Argentina", title:"San Nicolás quedó atrás: la mira, puesta en Concordia", text:"Tras San Nicolás, el Campeonato Argentino de Velocidad afronta un nuevo capítulo de la temporada 2026 en Concordia, del 7 al 9 de agosto. Cada punto puede marcar la diferencia.", imagen:"NOTICIAS-IG/DaxjP-LIap2.jpg", ig:"DaxjP-LIap2" }
];
